### PR TITLE
Update zlib pointer.

### PR DESCRIPTION
**Pull request by whchung**
According to https://www.zlib.net/ , zlib has been upgraded to 1.2.12. 1.2.11 is no longer available.

### CODE REVIEW

**Comment by whchung** [comment]
https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1483

**Comment by whchung** [comment]
@junliume / @pfultz2 Please help assess should we should zlib 1.2.12. MIOpen build is currently broken because 1.2.11 is no longer available.

**Comment by junliume** [comment]
@whchung I don't think this will fix the issue since http://zigzag.amd.com/ is offline. CC: @JehandadKhan 
The "safe" choice now would be:

- [ ] download http://zlib.net/fossils/zlib-1.2.11.tar.gz
- [ ] change all zigzag to ginger? Or we really wish to revive zigzag? @JehandadKhan @okakarpa 

**[New Update]**
How about combining these changes?

- [ ] Update https://github.com/ROCmSoftwarePlatform/rocm-recipes/blob/master/recipes/zlib/package.txt#L1 to use 1.2.12.
- [ ] Update all "zigzag" to "ginger" @okakarpa firewall issues resolved yet?
- [ ] Upload all dependencies to "ginger" 

@whchung Please let me know if you have time, or wish me or someone in MIOpen to make these changes. :) Thanks!

**Review by pfultz2 — APPROVED** [review]

**Review by junliume — APPROVED** [review]
I hope we have a way to test this solution before merging. It seems that the change will be ported into MIOpen without MIOpen itself bumping its version or any visible controls.

Remaining tasks after this fix:
- [ ] Update all "zigzag" to "ginger" @okakarpa firewall issues needs to be resolved, currently there is already a ticket
- [ ] Upload all dependencies to "ginger" (we can do this in parallel with the above)

**Comment by pfultz2** [comment]
> I hope we have a way to test this solution before merging.

I tested zlib locally.

**Pull request merged**
